openapi: 3.0.0
info:
  title: API de Gestión de Usuarios y Suscripciones
  version: 1.0.0
  description: API para gestionar información de usuarios y suscripciones en un sistema SaaS.
servers:
  - url: https://consultor-api.coderoom.cl

paths:
  /api/subscriptions:
    post:
      summary: Crear un Usuario con Suscripciones o Actualizar Información de Usuario
      description: Crea un nuevo usuario o actualiza la información de usuario existente. Si el usuario ya existe y la contraseña está vacía, se actualizará el resto de la información.
      requestBody:
        description: Información del usuario y suscripciones.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithSubscriptions'
      responses:
        '201':
          description: Usuario creado o actualizado exitosamente.
        '400':
          description: Solicitud incorrecta - Datos de entrada inválidos.
        '500':
          description: Error interno del servidor.

    put:
      summary: Actualizar Información de Usuario y Suscripciones
      description: Actualiza la información de usuario existente, incluyendo suscripciones.
      requestBody:
        description: Información del usuario y suscripciones.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithSubscriptions'
      responses:
        '200':
          description: Usuario y suscripciones actualizados exitosamente.
        '400':
          description: Solicitud incorrecta - Datos de entrada inválidos.
        '404':
          description: Usuario no encontrado.
        '500':
          description: Error interno del servidor.

components:
  schemas:
    UserWithSubscriptions:
      type: object
      properties:
        userID:
          type: string
          description: El identificador único del usuario.
        password:
          type: string
          description: La contraseña del usuario.
        name:
          type: string
          description: El nombre completo del usuario.
        email:
          type: string
          format: email
          description: La dirección de correo electrónico del usuario.
        subscriptions:
          type: array
          description: Un array de suscripciones del usuario.
          items:
            type: object
            properties:
              startDate:
                type: string
                format: date-time
                description: La fecha de inicio de la suscripción.
              endDate:
                type: string
                format: date-time
                description: La fecha de finalización de la suscripción.
              plan:
                type: string
                enum: [LABORAL, TRIBUTARIO]
                description: El tipo de plan de suscripción (LABORAL o TRIBUTARIO).
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
